/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IssueSubmitter.java
 *
 * Created on Jan 7, 2011, 3:59:49 PM
 */

package wheelencodergenerator;

import java.awt.Frame;

/**
 *
 * @author Michael Shimniok
 */
public class IssueDialog extends javax.swing.JDialog {

    public static final int SUBMIT_OPTION = 1;
    public static final int CANCEL_OPTION = 0;

    public int answer = CANCEL_OPTION;

    /** Creates new form IssueSubmitter */
    public IssueDialog(Frame frame, String title) {
        super(frame, title);
        initComponents();
    }

    public int getAnswer() {
        return this.answer;
    }

    public String getSummary() {
        return issueSummary.getText();
    }

    public String getDescription() {
        return issueDescription.getText();
    }

    public String getIssueType() {
        return issueType.getSelectedItem().toString();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        issueType = new javax.swing.JComboBox();
        issueSummary = new javax.swing.JTextField();
        issueDescription = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        issueSubmit = new java.awt.Button();
        issueCancel = new java.awt.Button();

        setMinimumSize(new java.awt.Dimension(400, 280));
        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("Form"); // NOI18N

        jLabel1.setName("jLabel1"); // NOI18N

        issueType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Defect", "Enhancement" }));
        issueType.setName("issueType"); // NOI18N
        issueType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueTypeActionPerformed(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wheelencodergenerator.WheelEncoderGeneratorApp.class).getContext().getResourceMap(IssueDialog.class);
        issueSummary.setText(resourceMap.getString("issueSummary.text")); // NOI18N
        issueSummary.setName("issueSummary"); // NOI18N

        issueDescription.setName("issueDescription"); // NOI18N

        jLabel2.setName("jLabel2"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        issueSubmit.setLabel(resourceMap.getString("issueSubmit.label")); // NOI18N
        issueSubmit.setName("issueSubmit"); // NOI18N
        issueSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit(evt);
            }
        });
        jPanel1.add(issueSubmit);

        issueCancel.setLabel(resourceMap.getString("issueCancel.label")); // NOI18N
        issueCancel.setName("issueCancel"); // NOI18N
        issueCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel(evt);
            }
        });
        jPanel1.add(issueCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueType, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueSummary, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(issueDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(issueType, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issueDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issueTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueTypeActionPerformed

    private void submit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit
        this.answer = SUBMIT_OPTION;
        setVisible(false);
    }//GEN-LAST:event_submit

    private void cancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel
        this.answer = CANCEL_OPTION;
        setVisible(false);
    }//GEN-LAST:event_cancel


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button issueCancel;
    private java.awt.TextArea issueDescription;
    private java.awt.Button issueSubmit;
    private javax.swing.JTextField issueSummary;
    private javax.swing.JComboBox issueType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
